//! Wire-compat byte fixture tests.
//!
//! Each test loads a Go-produced fixture (JSON or binary), deserializes it
//! into the corresponding rustscale type, re-serializes, and asserts
//! byte-identical output. This is the regression gate for the wire layer:
//! any serde rename, field-order change, or skip-rule drift that diverges
//! from Go's `encoding/json` output will fail here.
//!
//! Fixtures are generated by `tools/gen-wire-fixtures.sh` (which runs a Go
//! program against the Tailscale Go repo). See `fixtures/README.md` for
//! regeneration instructions.
//!
//! Known wire-compat bugs found during fixture creation — all fixed:
//!
//! 1. **RegisterRequest was missing Go fields `NLKey` and `NodeKeySignature`**.
//!    Fixed: added `NLKey: NLPublic` (serializes as `nlpub:<hex>`) and
//!    `NodeKeySignature: Option<Vec<u8>>` (base64, always present).
//!
//! 2. **RegisterResponse was missing Go field `NodeKeySignature`**.
//!    Fixed: added `NodeKeySignature: Option<Vec<u8>>` (base64, always present).
//!
//! 3. **SSH types used PascalCase JSON keys in Rust but camelCase in Go**.
//!    Fixed: added `#[serde(rename)]` attributes matching Go's json tags.
//!
//! 4. **SSHAction.SessionDuration used seconds in Rust but nanoseconds in Go**.
//!    Fixed: changed `duration_secs` to `duration_nanos` (i64 nanoseconds).
//!
//! 5. **FilterRule.SrcIPs had `skip_serializing_if = Vec::is_empty` but Go
//!    always emits**. Fixed: removed the skip rule.
//!
//! 6. **Hostinfo field order differed from Go**. Fixed: reordered to match
//!    Go's struct field order.
//!
//! 7. **MapRequest.DiscoKey had `skip_serializing_if = skip_zero_disco` but
//!    Go always emits**. Fixed: removed the skip rule.
//!
//! 8. **Node.KeySignature serialized as JSON array in Rust but base64 in Go**.
//!    Fixed: added `base64_bytes` serde helper for `Option<Vec<u8>>`.

use rustscale_wire_fixture::{assert_binary_roundtrip, assert_json_roundtrip};

// ─── JSON fixture tests (Go-generated, byte-identical comparison) ───

#[test]
fn node_full() {
    let json = include_str!("../fixtures/node_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::Node>(json);
}

#[test]
fn hostinfo_full() {
    let json = include_str!("../fixtures/hostinfo_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::Hostinfo>(json);
}

#[test]
fn derp_map_full() {
    let json = include_str!("../fixtures/derp_map_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::DERPMap>(json);
}

#[test]
fn dns_config_full() {
    let json = include_str!("../fixtures/dns_config_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::DNSConfig>(json);
}

#[test]
fn map_request_minimal() {
    let json = include_str!("../fixtures/map_request_minimal.json");
    assert_json_roundtrip::<rustscale_tailcfg::MapRequest>(json);
}

#[test]
fn map_request_full() {
    let json = include_str!("../fixtures/map_request_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::MapRequest>(json);
}

#[test]
fn map_response_full() {
    let json = include_str!("../fixtures/map_response_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::MapResponse>(json);
}

#[test]
fn map_response_peers_changed() {
    let json = include_str!("../fixtures/map_response_peers_changed.json");
    assert_json_roundtrip::<rustscale_tailcfg::MapResponse>(json);
}

#[test]
fn map_response_peers_removed() {
    let json = include_str!("../fixtures/map_response_peers_removed.json");
    assert_json_roundtrip::<rustscale_tailcfg::MapResponse>(json);
}

#[test]
fn map_response_peer_change_patch() {
    let json = include_str!("../fixtures/map_response_peer_change_patch.json");
    assert_json_roundtrip::<rustscale_tailcfg::MapResponse>(json);
}

#[test]
fn peer_change_full() {
    let json = include_str!("../fixtures/peer_change_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::PeerChange>(json);
}

#[test]
fn client_version_full() {
    let json = include_str!("../fixtures/client_version_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::ClientVersion>(json);
}

#[test]
fn user_profile_full() {
    let json = include_str!("../fixtures/user_profile_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::UserProfile>(json);
}

#[test]
fn net_info_full() {
    let json = include_str!("../fixtures/net_info_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::NetInfo>(json);
}

#[test]
fn filter_full() {
    let json = include_str!("../fixtures/filter_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::FilterRule>(json);
}

#[test]
fn null_slice() {
    // Exercises Go nil slice → JSON {} (all fields omitted by omitempty).
    // rustscale's deserialize_null_to_default should handle null slices.
    let json = include_str!("../fixtures/null_slice.json");
    assert_json_roundtrip::<rustscale_tailcfg::MapResponse>(json);
}

// ─── JSON fixture tests (previously subset, now full roundtrip) ───

#[test]
fn register_request_full() {
    let json = include_str!("../fixtures/register_request_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::RegisterRequest>(json);
}

#[test]
fn register_request_minimal() {
    let json = include_str!("../fixtures/register_request_minimal.json");
    assert_json_roundtrip::<rustscale_tailcfg::RegisterRequest>(json);
}

#[test]
fn register_response_full() {
    let json = include_str!("../fixtures/register_response_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::RegisterResponse>(json);
}

// ─── JSON fixture tests (hand-constructed) ───

#[test]
fn ssh_policy_full() {
    // Hand-constructed using Rust's PascalCase JSON keys (NOT Go-generated).
    // Go's SSH types use camelCase json tags ("rules", "principals",
    // "sshUsers", "action", etc.) but rustscale uses PascalCase without
    // serde rename. See bug #3 in module docs.
    let json = include_str!("../fixtures/ssh_policy_full.json");
    assert_json_roundtrip::<rustscale_tailcfg::SSHPolicy>(json);
}

// ─── Binary fixture tests (disco) ───

#[test]
fn disco_ping() {
    let bin = include_bytes!("../fixtures/disco_ping.bin");
    let msg = rustscale_disco::Message::parse(bin).expect("parse disco_ping");
    let re_encoded = msg.marshal();
    assert_binary_roundtrip(bin, &re_encoded);
}

#[test]
fn disco_pong() {
    let bin = include_bytes!("../fixtures/disco_pong.bin");
    let msg = rustscale_disco::Message::parse(bin).expect("parse disco_pong");
    let re_encoded = msg.marshal();
    assert_binary_roundtrip(bin, &re_encoded);
}

#[test]
fn disco_call_me_maybe() {
    let bin = include_bytes!("../fixtures/disco_call_me_maybe.bin");
    let msg = rustscale_disco::Message::parse(bin).expect("parse disco_call_me_maybe");
    let re_encoded = msg.marshal();
    assert_binary_roundtrip(bin, &re_encoded);
}

// ─── Binary fixture tests (DERP frame) ───

#[test]
fn derp_frame() {
    let bin = include_bytes!("../fixtures/derp_frame.bin");
    // A DERP frame is: 1-byte type + 4-byte BE length + payload.
    let header_len = rustscale_derp::FRAME_HEADER_LEN;
    assert!(bin.len() >= header_len, "derp_frame.bin too short");

    let mut header = [0u8; 5];
    header.copy_from_slice(&bin[..header_len]);
    let (typ, len) = rustscale_derp::decode_frame_header(&header);
    assert_eq!(
        len as usize + header_len,
        bin.len(),
        "declared length matches file"
    );

    // Re-encode the header.
    let re_encoded_header = rustscale_derp::encode_frame_header(typ, len);
    assert_binary_roundtrip(&header, &re_encoded_header);

    // Full frame: header + payload.
    let mut re_encoded = re_encoded_header.to_vec();
    re_encoded.extend_from_slice(&bin[header_len..]);
    assert_binary_roundtrip(bin, &re_encoded);
}

// ─── Binary fixture tests (STUN) ───

#[test]
fn stun_binding_response() {
    let bin = include_bytes!("../fixtures/stun_binding_response.bin");
    let (tx_id, addr) =
        rustscale_netcheck::parse_response(bin).expect("parse stun_binding_response");
    let re_encoded = rustscale_netcheck::response(&tx_id, addr);
    assert_binary_roundtrip(bin, &re_encoded);
}
